databases:
  - name: perfumeria_db
    databaseName: perfumeria
    user: perfumeria_user
    plan: free
    region: oregon

services:
  - type: web
    name: perfumeria-app
    runtime: docker


    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: perfumeria_db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
    region: oregon
    plan: free
