databases:
  - name: perfumeria_db
    databaseName: perfumeria
    user: perfumeria_user
    plan: free
    region: oregon

services:
  - type: web
    name: perfumeria-app
    runtime: docker


    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: perfumeria_db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
    region: oregon
    plan: free
